version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=examplepassword
      - MYSQL_DATABASE=mydb
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
  mysql:
    env_file:
      - mysql/.env
    build:
      context: .
      dockerfile: mysql/Dockerfile
    ports:
      - "3306:3306"
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
